"""
twin.py

The actual Digital Twin: stateful simulation of inventory, replenishment
orders, supplier lead time and stockouts for retail store-item entities.

Variable provenance (see project README for full definitions):
  OBSERVED   -> date, store, item, sales (from train.csv, historical only)
  DERIVED    -> predicted_demand (forecasting.py, XGBoost model output)
  SIMULATED  -> inventory, pending_orders, safety_stock, reorder_point,
                actual_demand, stockouts, service_level
                (none of these exist in the source dataset -- they are
                 generated by this module's policy logic)
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional
import math
import numpy as np
import pandas as pd

# Approximate inverse-normal z-scores for common service level targets.
# Avoids a scipy dependency for a small lookup.
_Z_TABLE = {
    0.50: 0.00, 0.80: 0.84, 0.85: 1.04, 0.90: 1.28,
    0.95: 1.645, 0.975: 1.96, 0.98: 2.05, 0.99: 2.33, 0.995: 2.58,
}


def z_for_service_level(service_level: float) -> float:
    keys = sorted(_Z_TABLE.keys())
    if service_level <= keys[0]:
        return _Z_TABLE[keys[0]]
    if service_level >= keys[-1]:
        return _Z_TABLE[keys[-1]]
    # linear interpolation between nearest table entries
    for lo, hi in zip(keys, keys[1:]):
        if lo <= service_level <= hi:
            frac = (service_level - lo) / (hi - lo)
            return _Z_TABLE[lo] + frac * (_Z_TABLE[hi] - _Z_TABLE[lo])
    return 1.645  # fallback, ~95%


@dataclass
class ScenarioConfig:
    name: str = "Baseline"
    demand_multiplier: float = 1.0      # e.g. 1.30 = demand surge +30%
    lead_time_change_days: int = 0      # e.g. +2 = supply disruption
    service_level_target: float = 0.95  # drives safety stock via z-score
    demand_noise_std_factor: float = 0.15  # simulated day-to-day volatility
    random_seed: int = 42


@dataclass
class SupplierConfig:
    base_lead_time_days: int = 5
    order_coverage_days: int = 14  # each order covers ~N days of avg demand

    def effective_lead_time(self, scenario: ScenarioConfig) -> int:
        return max(1, self.base_lead_time_days + scenario.lead_time_change_days)


@dataclass
class PendingOrder:
    quantity: float
    order_date: pd.Timestamp
    arrival_date: pd.Timestamp


@dataclass
class StoreItemTwin:
    store: int
    item: int
    scenario: ScenarioConfig
    supplier: SupplierConfig

    avg_daily_demand: float
    demand_std: float

    inventory: float = 0.0
    safety_stock: float = 0.0
    reorder_point: float = 0.0
    order_quantity: float = 0.0

    pending_orders: List[PendingOrder] = field(default_factory=list)
    event_log: List[Dict] = field(default_factory=list)

    cumulative_demand: float = 0.0
    cumulative_fulfilled: float = 0.0
    cumulative_unmet: float = 0.0
    stockout_days: int = 0
    replenishment_orders_placed: int = 0
    day_index: int = 0

    inventory_history: List[float] = field(default_factory=list)
    demand_history: List[float] = field(default_factory=list)
    predicted_demand_history: List[float] = field(default_factory=list)
    service_level_history: List[float] = field(default_factory=list)

    _rng: Optional[np.random.Generator] = field(default=None, repr=False)

    def __post_init__(self):
        self._rng = np.random.default_rng(self.scenario.random_seed + self.store * 1000 + self.item)

        # IMPORTANT: the inventory POLICY (safety stock, reorder point, order
        # quantity, starting inventory) is sized using NORMAL/baseline demand
        # and the supplier's BASE lead time -- not the scenario's disrupted
        # values. A retailer sets its stocking policy under normal
        # assumptions; a demand surge or supply disruption is a shock that
        # hits an already-fixed policy, not something the policy pre-adapts
        # to. This is what makes baseline vs. scenario a fair comparison:
        # both start from the identical initial state.
        baseline_lead_time = self.supplier.base_lead_time_days
        z = z_for_service_level(self.scenario.service_level_target)

        # Safety stock: z * demand_std * sqrt(lead_time)  (section 5 of spec)
        self.safety_stock = z * self.demand_std * math.sqrt(baseline_lead_time)

        # Reorder point: expected demand during lead time + safety stock
        expected_demand_during_lt = self.avg_daily_demand * baseline_lead_time
        self.reorder_point = expected_demand_during_lt + self.safety_stock

        # Order quantity: covers order_coverage_days of average (normal) demand
        self.order_quantity = max(
            1.0, self.avg_daily_demand * self.supplier.order_coverage_days,
        )

        # Initial inventory: a typical mid-cycle snapshot (not freshly
        # topped-up, not right at the reorder point) -- roughly halfway
        # through a normal order cycle.
        self.inventory = self.reorder_point + self.order_quantity / 2.0

        self._log(pd.NaT, "twin_initialized",
                  f"Store {self.store} / Item {self.item}: initial inventory="
                  f"{self.inventory:.0f}, reorder_point={self.reorder_point:.0f}, "
                  f"safety_stock={self.safety_stock:.0f}, base_lead_time={baseline_lead_time}d, "
                  f"order_qty={self.order_quantity:.0f} [sized on normal demand -- "
                  f"scenario '{self.scenario.name}' applies from day 1 onward]")

    def _log(self, day_date, event_type, message):
        self.event_log.append({
            "day": self.day_index,
            "date": str(day_date.date()) if pd.notna(day_date) else None,
            "store": self.store,
            "item": self.item,
            "event_type": event_type,
            "message": message,
        })

    def step(self, day_date: pd.Timestamp, predicted_demand_today: float):
        """
        Advances the twin by exactly one simulated day.
        Order of operations: arrivals -> demand -> fulfillment -> reorder check.
        """
        self.day_index += 1
        lead_time = self.supplier.effective_lead_time(self.scenario)

        # 1) Receive any orders arriving today
        still_pending = []
        for order in self.pending_orders:
            if order.arrival_date <= day_date:
                self.inventory += order.quantity
                self._log(day_date, "order_arrived",
                          f"Shipment of {order.quantity:.0f} units arrived "
                          f"(placed {order.order_date.date()}). Inventory -> {self.inventory:.0f}")
            else:
                still_pending.append(order)
        self.pending_orders = still_pending

        # 2) Simulated actual demand = model prediction (scenario-adjusted) + noise
        #    NOTE: this is SIMULATED, not observed -- there is no ground-truth
        #    sales figure for future/simulation dates.
        base = predicted_demand_today * self.scenario.demand_multiplier
        noise = self._rng.normal(0, self.demand_std * self.scenario.demand_noise_std_factor)
        actual_demand = max(0.0, base + noise)

        if actual_demand > predicted_demand_today * self.scenario.demand_multiplier * 1.15:
            self._log(day_date, "demand_spike",
                      f"Demand ({actual_demand:.0f}) exceeded forecast "
                      f"({predicted_demand_today * self.scenario.demand_multiplier:.0f}) by "
                      f">{((actual_demand / max(predicted_demand_today * self.scenario.demand_multiplier, 1e-6)) - 1) * 100:.0f}%")

        # 3) Fulfill demand from available inventory
        fulfilled = min(self.inventory, actual_demand)
        unmet = actual_demand - fulfilled
        self.inventory -= fulfilled

        self.cumulative_demand += actual_demand
        self.cumulative_fulfilled += fulfilled
        self.cumulative_unmet += unmet

        if unmet > 0:
            self.stockout_days += 1
            self._log(day_date, "stockout",
                      f"Stockout: {unmet:.0f} units unmet demand.")

        # 4) Reorder check: place a new order only if none currently pending
        #    (simple single-outstanding-order (s, S)-style policy, kept
        #    transparent/deterministic for demo purposes).
        if self.inventory <= self.reorder_point and not self.pending_orders:
            arrival = day_date + pd.Timedelta(days=lead_time)
            self.pending_orders.append(PendingOrder(
                quantity=self.order_quantity, order_date=day_date, arrival_date=arrival,
            ))
            self.replenishment_orders_placed += 1
            self._log(day_date, "order_placed",
                      f"Inventory ({self.inventory:.0f}) at/below reorder point "
                      f"({self.reorder_point:.0f}). Order placed: {self.order_quantity:.0f} "
                      f"units, arriving in {lead_time}d ({arrival.date()}).")

        # recovery note
        if self.inventory >= self.safety_stock and self.stockout_days > 0 and unmet == 0 \
                and len(self.demand_history) > 0 and self.inventory_history and self.inventory_history[-1] < self.safety_stock:
            self._log(day_date, "inventory_recovered",
                      f"Inventory recovered above safety stock threshold ({self.safety_stock:.0f}).")

        # 5) Record history
        self.inventory_history.append(self.inventory)
        self.demand_history.append(actual_demand)
        self.predicted_demand_history.append(predicted_demand_today)
        service_level = (self.cumulative_fulfilled / self.cumulative_demand) if self.cumulative_demand > 0 else 1.0
        self.service_level_history.append(service_level)

        return {
            "day": self.day_index,
            "date": day_date,
            "store": self.store,
            "item": self.item,
            "inventory": self.inventory,
            "predicted_demand": predicted_demand_today,
            "actual_demand": actual_demand,
            "fulfilled_demand": fulfilled,
            "unmet_demand": unmet,
            "stockout": unmet > 0,
            "pending_orders": len(self.pending_orders),
            "reorder_point": self.reorder_point,
            "safety_stock": self.safety_stock,
            "service_level": service_level,
        }

    def summary(self) -> Dict:
        service_level = (self.cumulative_fulfilled / self.cumulative_demand) if self.cumulative_demand > 0 else 1.0
        return {
            "store": self.store,
            "item": self.item,
            "scenario": self.scenario.name,
            "days_simulated": self.day_index,
            "total_demand": round(self.cumulative_demand, 1),
            "fulfilled_demand": round(self.cumulative_fulfilled, 1),
            "unmet_demand": round(self.cumulative_unmet, 1),
            "service_level": round(service_level, 4),
            "stockout_days": self.stockout_days,
            "stockout_rate": round(self.stockout_days / max(self.day_index, 1), 4),
            "average_inventory": round(float(np.mean(self.inventory_history)), 1) if self.inventory_history else 0,
            "min_inventory": round(float(np.min(self.inventory_history)), 1) if self.inventory_history else 0,
            "max_inventory": round(float(np.max(self.inventory_history)), 1) if self.inventory_history else 0,
            "replenishment_orders": self.replenishment_orders_placed,
            "reorder_point": round(self.reorder_point, 1),
            "safety_stock": round(self.safety_stock, 1),
        }


class DigitalTwin:
    """
    Network-level Digital Twin: owns one StoreItemTwin per (store, item)
    and steps them together, day by day, across the whole retail network.
    """

    def __init__(self, store_item_pairs, scenario: ScenarioConfig,
                 supplier: SupplierConfig, demand_stats: Dict, predicted_demand_df: pd.DataFrame):
        """
        demand_stats: {(store, item): (avg_daily_demand, demand_std)}
        predicted_demand_df: long df with date, store, item, predicted_demand
                              (output of forecasting.recursive_forecast)
        """
        self.scenario = scenario
        self.supplier = supplier
        self.entities: Dict[tuple, StoreItemTwin] = {}

        for (store, item) in store_item_pairs:
            avg_d, std_d = demand_stats[(store, item)]
            self.entities[(store, item)] = StoreItemTwin(
                store=store, item=item, scenario=scenario, supplier=supplier,
                avg_daily_demand=avg_d, demand_std=max(std_d, 1e-6),
            )

        self._pred = predicted_demand_df.set_index(["date", "store", "item"])["predicted_demand"]
        self.dates = sorted(predicted_demand_df["date"].unique())
        self.current_day_idx = 0

    def step_all(self):
        """Advance every entity by exactly one simulated day. Returns list of step dicts."""
        if self.current_day_idx >= len(self.dates):
            return None
        day_date = pd.Timestamp(self.dates[self.current_day_idx])
        results = []
        for key, twin in self.entities.items():
            try:
                pred = float(self._pred.loc[(day_date, key[0], key[1])])
            except KeyError:
                pred = twin.avg_daily_demand  # fallback, shouldn't normally happen
            results.append(twin.step(day_date, pred))
        self.current_day_idx += 1
        return results

    def run(self, horizon_days: Optional[int] = None):
        """Run the twin to completion (or horizon_days), returns full step history as DataFrame."""
        limit = horizon_days if horizon_days is not None else len(self.dates)
        all_steps = []
        for _ in range(min(limit, len(self.dates) - self.current_day_idx)):
            step_results = self.step_all()
            if step_results is None:
                break
            all_steps.extend(step_results)
        return pd.DataFrame(all_steps)

    def network_summary(self) -> pd.DataFrame:
        return pd.DataFrame([t.summary() for t in self.entities.values()])

    def all_events(self) -> pd.DataFrame:
        rows = []
        for t in self.entities.values():
            rows.extend(t.event_log)
        df = pd.DataFrame(rows)
        if len(df):
            df = df.sort_values("day").reset_index(drop=True)
        return df
